version: "3.8"

services:
  # Application service: Express app running on Node.js
  app:
    container_name: admin-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose port 8000 for the application (from .env)
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    volumes:
      - .:/app # Bind current directory to /app inside the container
      - /app/node_modules # Persist node_modules folder
    networks:
      - app-network

  # Test service for running tests
  test:
    build: .
    command: npm test # Run tests when the container starts
    volumes:
      - .:/app # Bind current directory to /app inside the container
      - /app/node_modules # Persist node_modules folder
    depends_on:
      - redis # Ensure Redis starts before the test service
    environment: NODE_ENV=test # Set environment to test for this service

# Define a network for inter-container communication
networks:
  app-network:
    driver: bridge
